apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autoscaling-web-platform
  description: Production-grade auto-scaling web platform with Terraform (AWS), Ansible blue-green deployment, and Python orchestrator with auto-rollback
  annotations:
    github.com/project-slug: sonujha78/autoscaling-web-platform
    backstage.io/kubernetes-id: autoscaling-web-platform
    argocd/app-name: autoscaling-web-platform
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/sonujha78/autoscaling-web-platform
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: autoscaling-platform
  dependsOn:
    - resource:default/autoscaling-alb
